include:
  - project: "devops/gitlab/ci-templates/docker"
    ref: "master"
    file: ".build_docker_image.yml"
  - project: "devops/gitlab/ci-templates/docker"
    ref: "master"
    file: ".push_docker_image.yml"
  - project: "devops/gitlab/ci-templates/docker"
    ref: "master"
    file: ".remove_docker_image.yml"
  - project: "devops/gitlab/ci-templates/sast"
    ref: "master"
    file: ".shiftleft_container_scanning.yml"
  - project: "devops/gitlab/ci-templates/sast"
    ref: "master"
    file: ".trivy_container_scanning.yml"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID

stages:
  - .pre
  - sast
  - push
  - .post

build_image:
  stage: .pre
  extends:
    - .build_docker_image
  tags:
    - build

shiftleft_container_scanning:
  stage: sast
  extends:
    - .shiftleft_container_scanning
  tags:
    - build
  allow_failure: true

trivy_container_scanning:
  stage: sast
  extends:
    - .trivy_container_scanning
  tags:
    - build
  allow_failure: true

push_image_to_registry:
  stage: push
  extends:
    - .push_docker_image
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - build

remove_image:
  stage: .post
  extends:
    - .remove_docker_image
  rules:
    - when: always
  tags:
    - build
