title = "gitleaks config"

[[regexes]]
description = "Password in string"
regex = '''(?i)[\w]*password[\w]*[:=>, ]+['"][\S]{2,}['"]'''
[[regexes]]
description = "Password in YAML config"
regex = '''^(?i)[\w]*password[\w][: ]+[\S]{2,}[^,}]$'''
[[regexes]]
description = "Alma API key"
regex = '''(?i)alma_key.*[0-9a-zA-Z]{36}'''
[[regexes]]
description = "AWS"
regex = '''AKIA[0-9A-Z]{16}'''
[[regexes]]
description = "RKCS8"
regex = '''-----BEGIN PRIVATE KEY-----'''
[[regexes]]
description = "RSA"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''
[[regexes]]
description = "Github"
regex = '''(?i)github.*['\"][0-9a-zA-Z]{35,40}['\"]'''
[[regexes]]
description = "SSH"
regex = '''-----BEGIN OPENSSH PRIVATE KEY-----'''
[[regexes]]
description = "Facebook"
regex = '''(?i)facebook.*['\"][0-9a-f]{32}['\"]'''
[[regexes]]
description = "Twitter"
regex = '''(?i)twitter.*['\"][0-9a-zA-Z]{35,44}['\"]'''
[[regexes]]
description = "PGP"
regex = '''-----BEGIN PGP PRIVATE KEY BLOCK-----'''
[[regexes]]
description = "Slack token"
regex = '''xox[baprs]-.*'''
[[regexes]]
description = "Strip API Key"
regex = '''(?i)(sk|pk)_(test|live)_[0-9a-zA-Z]{10,32}'''

[whitelist]
commits = []
files = [
  '\.gitleaks\.toml',
  '\.env\.example',
  '(.*?)(jpg|gif|doc|pdf|bin|md)$',
]
regexes = [
  # Values set by environment variables
  '''ENV\[['"][\S]+['"]\]''',
]
