version: "3.2"

services:
  db:
    image: "mysql/mysql-server:5.7"
    env_file: ".env"
    networks:
      - marmite
    restart: "unless-stopped"
    volumes:
      - "db:/var/lib/mysql"
  sinatra:
    image: "gitlab.library.upenn.edu/dld/digital-repository/marmite:v1-4-2"
    depends_on:
      - "db"
    env_file:
      - ".env"
    networks:
      - marmite
    ports:
      - "9292:9292"
    restart: "unless-stopped"

networks:
  marmite:

volumes:
  db:
