version: '2'

services:
  db:
    restart: 'unless-stopped'
    image: 'mysql/mysql-server:5.7'
    env_file: '.env'
    volumes:
      - 'db:/var/lib/mysql'
  sinatra:
    restart: 'unless-stopped'
    depends_on:
      - 'db'
    image: 'quay.io/upennlibraries/marmite:e94a364'
    ports:
      - '9292:9292'
    env_file:
      - '.env'
    volumes:
      - 'nfs:/var/nfs'
    links:
      - 'db'

volumes:
  db:
  nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_ADDR},rw
      device: "${NFS_DEVICE}"
