version: '2'

services:
  db:
    restart: 'unless-stopped'
    image: 'mysql/mysql-server:5.7'
    env_file: '.env'
    volumes:
      - 'db:/var/lib/mysql'
  sinatra:
    restart: 'unless-stopped'
    depends_on:
      - 'db'
    image: 'gitlab.library.upenn.edu/digital-repository/marmite:v1-1-0'
    ports:
      - '9292:9292'
    env_file:
      - '.env'
    links:
      - 'db'

volumes:
  db:
