version: '3.7'

services:
  db:
    image: 'mysql/mysql-server:5.7'
    env_file: '.env'
    volumes:
      - 'db:/var/lib/mysql'
  sinatra:
    depends_on:
      - 'db'
    image: 'quay.io/upennlibraries/marmite:354a7e6'
    env_file: '.env'
    ports:
      - '9292:9292'
    env_file:
      - '.env'

volumes:
  db:
