version: 2.1

orbs:
  docker-publish: upenn-libraries/docker-publish@0.1.0
  gitleaks: upenn-libraries/gitleaks@0.1.1
  slack: circleci/slack@3.4.2

workflows:
  build_and_test:
    jobs:
      - gitleaks/check_local:
          image: quay.io/upennlibraries/gitleaks:v1.24.0
          options: --redact --repo-config
      - docker-publish/publish:
          context: quay.io
          registry: quay.io
          image: upennlibraries/marmite
          label_prefix: edu.upenn.library
          requires:
            - gitleaks/check_local
          post-steps:
            - run:
                environment:
                  GIT_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<< pipeline.git.revision >>
                command: |
                  echo "export GIT_COMMIT_DESC='$(git --git-dir /root/project/.git log --format=%B -n 1 $CIRCLE_SHA1)'" >> $BASH_ENV
                  source $BASH_ENV
            - slack/status:
                channel: marmite-notifications
                failure_message: ":red_circle: Failure! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
                success_message: ":tada: Success! ${CIRCLE_USERNAME}'s workflow (<${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>) in <${GIT_URL}|${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}>, Message: ${GIT_COMMIT_DESC}"
                webhook: ${SLACK_WEBHOOK}
