version: 2.1

orbs:
  docker-publish: upenn-libraries/docker-publish@0.1.0
  gitleaks: upenn-libraries/gitleaks@0.1.1

workflows:
  build_and_test:
    jobs:
      - gitleaks/check_local:
          image: quay.io/upennlibraries/gitleaks:v1.24.0
          options: --redact --repo-config
      - docker-publish/publish:
          context: quay.io
          registry: quay.io
          image: upennlibraries/marmite
          label_prefix: edu.upenn.library
