default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 40
  username: root
  password:
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: marc_alma_dev

test:
  <<: *default
  database: marc_alma_test

production:
  <<: *default
  host: db
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
