default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 40
  username: root
  password:
  host: 127.0.0.1
  port: 3308

development:
  <<: *default
  database: marmite_dev

test:
  <<: *default
  database: marmite_test

production:
  <<: *default
  host: db
  port: 3306
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
